### ISSUE TITLE
ownCloud needs write access to config directory

### ISSUE THREAD

**Issue by nnn-gif** [indiehosters/ownCloud#12]
Simply using docker-compose doesnt give write access to config directory,
there is need to give permission to ./data direcory, which nginx can access

**Comment by pierreozoux** [comment]
Hum, I don't understand.

Do you run docker-compose from the host of docker daemon?

I never encountered this particular issue.

If you can detail more, I could help you.

**Comment by nnn-gif** [comment]
yes running docker-compose from host of docker daemon

1)./install
2) docker-compose up -d

you can look into this url

http://40.121.85.198

**Comment by pierreozoux** [comment]
in the host, could you run:
`ls -lat ./data`

And confirm me that docker daemon is running with root.

**Comment by pierreozoux** [comment]
Do you still have the issue?

**Comment by unteem** [comment]
not maintained anymore moved to [nextcloud](https://lab.libreho.st/libre.sh/compose/nextcloud)
