### ISSUE TITLE
Cannot login with nginx.conf(non-ssl)

### ISSUE THREAD

**Issue by xzvfinet** [indiehosters/ownCloud#16]
I'm not a native English speaker, so please pardon me if I use wrong language.

After installation is finished, I tried to login with default admin but it failed.
I found a questionable sentence in the nginx.conf 
fastcgi_param HTTPS on;
Commenting this line solved my problems.
So I think that you are mistakenly put this.

**Comment by pierreozoux** [comment]
Hi!

Thanks for your feedback! This setup is used behing an TLS offloader indeed, so you might have issues to make it runngin without TLS. But I think you should use TLS.

Do you have any advice on how to rephrase to make it clearer?
I actually don't want to help pleople to host without TLS,but something like:
- if you want to use behind TLS, use the nginx.conf
- if you want to use directly, use the nginx-ssl.conf

What do you think?

**Comment by pierreozoux** [comment]
this is too old, closing
