### ISSUE TITLE
Access forbidden CSRF check failed

### ISSUE THREAD

**Issue by TribuneX** [indiehosters/ownCloud#21]
Hi,

I wanted to setup owncloud with your docker-compose file. I can run the different containers and install owncloud. However, if I try to login with the newly created account, it gives me the following error:

`Access forbidden
CSRF check failed`

Any idea why this is the case?

**Comment by unteem** [comment]
not maintained anymore moved to [nextcloud](https://lab.libreho.st/libre.sh/compose/nextcloud)
