### ISSUE TITLE
error while executing ./install

### ISSUE THREAD

**Issue by nnn-gif** [indiehosters/ownCloud#8]
./install gives following error

./install: line 9: URL: unbound variable

**Comment by pierreozoux** [comment]
Yes, you should provide to the install script:
URL
MAIL_HOST
MAIL_PORT
MAIL_DOMAIN
MAIL_PASS

It should be documented :/

```
URL=example.org ./install
```

**Comment by nnn-gif** [comment]
PR for there variables
